lib/tutoring_web/router.ex
defmodule TutoringWeb.Router do
  use TutoringWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TutoringWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/students", StudentController do
      resources "/classes", ClassController
    end
    resources "/classes", ClassController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TutoringWeb do
  #   pipe_through :api
  # end
end

lib/tutoring_web/views/layout_view.ex
defmodule TutoringWeb.LayoutView do
  use TutoringWeb, :view
end

lib/tutoring_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tutoring</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><%= link "Home", to: page_path(@conn, :index) %></li>
            <li><%= link "Students", to: student_path(@conn, :index) %></li>
            <li><%= link "Classes", to: class_path(@conn, :index) %></li>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>